name: Nightly Build

on:
  schedule:
    - cron: "0 14 * * *" # 2PM UTC
  workflow_dispatch:

concurrency:
  group: nightly
  cancel-in-progress: true

env:
  SOLUTION_FILE_PATH: ./yubx.sln
  BUILD_CONFIGURATION: Release
  PLATFORM: x64

jobs:
  check_recent_commit:
    runs-on: ubuntu-latest
    name: Check Recent Commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - id: should_run
        name: Check if latest commit date is within the previous 24 hours
        run: |
          if [ -z "$(git rev-list --since="24 hours ago" --all)" ]; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  build_nightly:
    runs-on: [self-hosted, Windows]
    name: Build Nightly
    needs: check_recent_commit
    if: needs.check_recent_commit.outputs.should_run == 'true'
    outputs:
      full_sha: ${{ steps.var.outputs.full_sha }}
      short_sha: ${{ steps.var.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

      - name: Build solution
        run: msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.PLATFORM }}

      - name: Find built executable
        id: find_exe
        shell: pwsh
        run: |
          $exe = Get-ChildItem -Path . -Recurse -Filter Injector.exe | Where-Object { $_.FullName -match "\\x64\\Release\\" } | Select-Object -First 1
          if (-not $exe) {
            Write-Error "Injector.exe not found in expected build output."
            exit 1
          }
          $relativePath = $exe.FullName.Substring("${{ github.workspace }}".Length + 1) -replace '\\', '/'
          echo "EXE_PATH=$relativePath" >> $env:GITHUB_ENV

      - name: Generate Build Info
        id: var
        shell: pwsh
        run: |
          echo "full_sha=$(git rev-parse HEAD)" >> $env:GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

  recreate_release:
    runs-on: ubuntu-latest
    name: Recreate Release
    needs: build_nightly
    if: needs.check_recent_commit.outputs.should_run == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Delete Existing Release
        id: delete_release
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const tag = "nightly";

            const releases = await github.rest.repos.listReleases({ owner, repo });
            const release = releases.data.find(r => r.tag_name === tag);

            if (release) {
              await github.rest.repos.deleteRelease({ owner, repo, release_id: release.id });
              console.log(`Deleted release with ID ${release.id}`);
            } else {
              console.log("No existing release to delete");
            }

            try {
              await github.rest.git.deleteRef({ owner, repo, ref: `tags/${tag}` });
              console.log(`Deleted tag ${tag}`);
            } catch (error) {
              console.error(`Error deleting tag: ${error.message}`);
            }

      - name: Download built executable
        uses: actions/download-artifact@v4
        with:
          name: binary
        continue-on-error: true # Safety in case no artifact uploaded

      - name: Echo build sha256
        id: build_sha
        run: |
          sha256sum ${{ env.EXE_PATH }} > sha256.checksum
          echo "build_sha=$(cat sha256.checksum)" >> $GITHUB_OUTPUT
          cat sha256.checksum

      - name: Nightly Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: Nightly [${{ needs.build_nightly.outputs.short_sha }}]
          tag_name: nightly
          body: |
            **This release has been built by GitHub Actions**
            [Link to build](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

            Build SHA256:
            ```
            ${{ steps.build_sha.outputs.build_sha }}
            ```

            These are nightly builds of Injector:
            - Helps verify recent changes
            - No warranties
            - Automatically replaced daily

            Full Commit Hash:
            ```
            ${{ needs.build_nightly.outputs.full_sha }}
            ```
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
